name: Sync chart manifest
on:
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created, edited]

jobs:
  check_chart_manifest_in_sync:
    if: github.event_name == 'pull_request'
    name: Check chart manifest in sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check helm template in sync
        id: helm_template
        run: |
          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
          if git diff --quiet && git diff --quiet --cached; then 
            echo "✅ Manifests are in sync"; 
          else 
            echo "❌ Manifest update required. Comment with '@meilisearch sync-manifest' to update automatically";
            exit 1
          fi

  sync_chart_manifest_on_comment:
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@meilisearch sync-manifest')
    name: Sync chart manifest
    runs-on: ubuntu-latest
    steps:
      # There isn't enough detail in the github.event on "issue_comment" events about the PR origin, so we need to fetch more
      - name: "Get Pull Request"
        uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}

      - name: Run helm template
        id: helm_template
        run: |
          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
          echo "::set-output name=has_changes::$(if git diff --quiet && git diff --quiet --cached; then echo "false"; else echo "true"; fi)"

      - name: Commit manifest changes
        if: steps.helm_template.outputs.has_changes == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "[CI] Syncing Helm manifest"
          git push --set-upstream origin ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
