name: Sync chart manifest
on:
  push:
    branches:
      - main

jobs:
  sync_chart_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run helm template
        id: helm_template
        run: |
          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
          echo "::set-output name=has_changes::$(if git diff --quiet && git diff --quiet --cached; then echo "false"; else echo "true"; fi)"

      - name: Commit manifest changes
        if: steps.helm_template.outputs.has_changes == 'true'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "[CI] Syncing Helm manifest"
          git push --set-upstream origin main
